const DBKEY="ghaim_fee_data_v1";
const empty={students:[],payments:[]};
function db(){try{return JSON.parse(localStorage.getItem(DBKEY))||empty}catch(e){return empty}}
function saveDB(d){localStorage.setItem(DBKEY,JSON.stringify(d))}
function money(n){return Number(n||0).toLocaleString("ar-SA")}
function today(){return new Date().toISOString().slice(0,10)}
function toggleMenu(){document.body.classList.toggle("open")}
function initDashboard(){const d=db();const paid=d.payments.reduce((s,p)=>s+Number(p.amount),0),fees=d.students.reduce((s,x)=>s+Number(x.fees),0);studentsCount.textContent=money(d.students.length);feesTotal.textContent=money(fees);paidTotal.textContent=money(paid);remainingTotal.textContent=money(Math.max(fees-paid,0));todayPayments.innerHTML=d.payments.filter(p=>p.date===today()).slice(-5).reverse().map(p=>{let s=d.students.find(x=>x.id===p.studentId);return row(p,s)}).join("")||'<div class="empty">لا توجد دفعات اليوم</div>';upcoming.innerHTML=buildSchedule(d).slice(0,5).map(x=>`<tr><td>${x.name}</td><td>${x.level}</td><td>${x.date}</td><td>${money(x.amount)} ريال</td><td><span class="status soon">قادمة</span></td></tr>`).join("")||'<tr><td colspan="5">لا توجد مواعيد مسجلة</td></tr>'}
function row(p,s){return `<div class="payment-row"><div class="person"><div class="avatar-sm">${(s?.name||"?").trim().charAt(0)}</div><div><b>${s?.name||"طالب محذوف"}</b><small>${s?.level||""} · ${p.date}</small></div></div><strong>${money(p.amount)} <small>ريال</small></strong><span class="method ${p.method==="بنكي"?"bank":p.method==="شبكة"?"network":p.method==="قرة"?"qara":"tabby"}">${p.method}</span></div>`}
function openStudent(){studentModal.classList.add("show");sName.focus()}function closeStudent(){studentModal.classList.remove("show")}
function saveStudent(){let name=sName.value.trim(),level=sLevel.value,fees=Number(sFees.value);if(!name||!fees)return alert("أدخل اسم الطالب وإجمالي الرسوم");let d=db();d.students.push({id:crypto.randomUUID(),name,level,fees,notes:sNotes.value.trim(),createdAt:today()});saveDB(d);closeStudent();sName.value="";sFees.value="";sNotes.value="";renderStudents();alert("تم حفظ الطالب")}
function renderStudents(){if(!window.studentsTable)return;let d=db(),q=(studentSearch?.value||"").trim(),l=levelFilter?.value||"";studentsTable.innerHTML=d.students.filter(s=>(!q||s.name.includes(q))&&(!l||s.level===l)).map(s=>{let paid=d.payments.filter(p=>p.studentId===s.id).reduce((a,p)=>a+Number(p.amount),0);return `<tr><td><b>${s.name}</b></td><td>${s.level}</td><td>${money(s.fees)} ريال</td><td>${money(paid)} ريال</td><td>${money(Math.max(s.fees-paid,0))} ريال</td><td><a class="link" href="student.html?id=${s.id}">الملف</a></td></tr>`}).join("")||'<tr><td colspan="6">لا توجد نتائج</td></tr>'}
function initPayment(){pDate.value=today();let d=db();pStudent.innerHTML='<option value="">اختر الطالب</option>'+d.students.map(s=>`<option value="${s.id}">${s.name} — ${s.level}</option>`).join("")}
function showBalance(){let d=db(),s=d.students.find(x=>x.id===pStudent.value);if(!s)return balanceBox.textContent="اختر الطالب لمعرفة المتبقي";let paid=d.payments.filter(p=>p.studentId===s.id).reduce((a,p)=>a+Number(p.amount),0);balanceBox.textContent=`إجمالي الرسوم: ${money(s.fees)} ريال · المدفوع: ${money(paid)} ريال · المتبقي: ${money(Math.max(s.fees-paid,0))} ريال`}
function savePayment(){let d=db(),sid=pStudent.value,amount=Number(pAmount.value);if(!sid||!amount)return alert("اختر الطالب وأدخل المبلغ");let s=d.students.find(x=>x.id===sid),paid=d.payments.filter(p=>p.studentId===sid).reduce((a,p)=>a+Number(p.amount),0);if(amount>Math.max(s.fees-paid,0))return alert("المبلغ أكبر من المتبقي على الطالب");d.payments.push({id:crypto.randomUUID(),studentId:sid,date:pDate.value||today(),amount,method:pMethod.value,ref:pRef.value.trim(),notes:pNotes.value.trim()});saveDB(d);alert("تم حفظ الدفعة بنجاح");location.href="payments.html"}
function renderPayments(){if(!window.paymentsTable)return;let d=db(),q=(paySearch?.value||"").trim(),l=payLevel?.value||"",m=payMethod?.value||"",f=fromDate?.value||"",t=toDate?.value||"";paymentsTable.innerHTML=d.payments.slice().sort((a,b)=>b.date.localeCompare(a.date)).filter(p=>{let s=d.students.find(x=>x.id===p.studentId);return (!q||s?.name.includes(q))&&(!l||s?.level===l)&&(!m||p.method===m)&&(!f||p.date>=f)&&(!t||p.date<=t)}).map(p=>{let s=d.students.find(x=>x.id===p.studentId);return `<tr><td>${p.date}</td><td>${s?.name||"-"}</td><td>${s?.level||"-"}</td><td>${money(p.amount)} ريال</td><td>${p.method}</td><td>${p.ref||"-"}</td></tr>`}).join("")||'<tr><td colspan="6">لا توجد عمليات</td></tr>'}
function addDays(date,n){let d=new Date(date+"T12:00:00");d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function weekday(date){return new Date(date+"T12:00:00").toLocaleDateString("ar-SA",{weekday:"long"})}
function nextWorkday(date){let d=date;for(let i=0;i<7;i++){let w=new Date(d+"T12:00:00").getDay();if(w!==5&&w!==6)return d;d=addDays(d,1)}}
function buildSchedule(d){let arr=[];d.students.forEach(s=>{let paid=d.payments.filter(p=>p.studentId===s.id).reduce((a,p)=>a+Number(p.amount),0),rem=s.fees-paid;if(rem<=0)return;let date=nextWorkday(addDays(today(),7));arr.push({name:s.name,level:s.level,date,day:weekday(date),amount:rem})});return arr.sort((a,b)=>a.date.localeCompare(b.date))}
function renderSchedule(){if(!window.scheduleTable)return;let d=db(),q=(schSearch?.value||"").trim(),l=schLevel?.value||"";scheduleTable.innerHTML=buildSchedule(d).filter(x=>(!q||x.name.includes(q))&&(!l||x.level===l)).map(x=>`<tr><td>${x.name}</td><td>${x.level}</td><td>${x.date}</td><td>${x.day}</td><td>${money(x.amount)} ريال</td></tr>`).join("")||'<tr><td colspan="5">لا توجد مواعيد</td></tr>'}
function renderReports(){let d=db(),fees=d.students.reduce((a,s)=>a+Number(s.fees),0),paid=d.payments.reduce((a,p)=>a+Number(p.amount),0);rStudents.textContent=money(d.students.length);rFees.textContent=money(fees);rPaid.textContent=money(paid);rRemain.textContent=money(Math.max(fees-paid,0));let methods=["بنكي","شبكة","قرة","تابي"];methodReport.innerHTML=methods.map(m=>{let x=d.payments.filter(p=>p.method===m);return `<tr><td>${m}</td><td>${x.length}</td><td>${money(x.reduce((a,p)=>a+Number(p.amount),0))} ريال</td></tr>`}).join("");levelReport.innerHTML=["تمهيدي","KG1","KG2"].map(l=>{let ss=d.students.filter(s=>s.level===l),ids=new Set(ss.map(s=>s.id)),pp=d.payments.filter(p=>ids.has(p.studentId)),f=ss.reduce((a,s)=>a+Number(s.fees),0),p=pp.reduce((a,x)=>a+Number(x.amount),0);return `<tr><td>${l}</td><td>${ss.length}</td><td>${money(f)}</td><td>${money(p)}</td><td>${money(Math.max(f-p,0))}</td></tr>`}).join("")}

const SETTINGS_KEY="ghaim_fee_settings_v1";
function settings(){try{return JSON.parse(localStorage.getItem(SETTINGS_KEY))||{levels:["تمهيدي","KG1","KG2"],methods:["بنكي","شبكة","قرة","تابي"]}}catch(e){return {levels:["تمهيدي","KG1","KG2"],methods:["بنكي","شبكة","قرة","تابي"]}}}
function saveSettings(x){localStorage.setItem(SETTINGS_KEY,JSON.stringify(x))}
function initStudentPage(){renderLevelOptions();renderStudents()}
function renderLevelOptions(){let x=settings().levels;if(window.levelFilter)levelFilter.innerHTML='<option value="">كل المستويات</option>'+x.map(v=>`<option>${v}</option>`).join("");if(window.sLevel)sLevel.innerHTML=x.map(v=>`<option>${v}</option>`).join("")}
function openStudent(id){studentModal.classList.add("show");let d=db(),s=d.students.find(x=>x.id===id);renderLevelOptions();if(s){studentModalTitle.textContent="تعديل بيانات الطالب";sId.value=s.id;sName.value=s.name;sLevel.value=s.level;sFees.value=s.fees;sNotes.value=s.notes||""}else{studentModalTitle.textContent="إضافة طالب";sId.value="";sName.value="";sFees.value="";sNotes.value=""}}
function closeStudent(){studentModal.classList.remove("show")}
function saveStudent(){let id=sId.value,name=sName.value.trim(),level=sLevel.value,fees=Number(sFees.value);if(!name||fees<0||!level)return alert("أكمل بيانات الطالب");let d=db();if(id){let s=d.students.find(x=>x.id===id);if(s){s.name=name;s.level=level;s.fees=fees;s.notes=sNotes.value.trim()}}else d.students.push({id:crypto.randomUUID(),name,level,fees,notes:sNotes.value.trim(),createdAt:today()});saveDB(d);closeStudent();renderStudents();alert(id?"تم تعديل بيانات الطالب":"تم حفظ الطالب")}
function deleteStudent(id){let d=db(),s=d.students.find(x=>x.id===id);if(!s)return;if(!confirm(`حذف الطالب "${s.name}"؟ سيتم حذف سجله المالي أيضًا.`))return;d.students=d.students.filter(x=>x.id!==id);d.payments=d.payments.filter(p=>p.studentId!==id);saveDB(d);renderStudents()}
function renderStudents(){if(!window.studentsTable)return;let d=db(),q=(studentSearch?.value||"").trim(),l=levelFilter?.value||"";studentsTable.innerHTML=d.students.filter(s=>(!q||s.name.includes(q))&&(!l||s.level===l)).map(s=>{let paid=d.payments.filter(p=>p.studentId===s.id).reduce((a,p)=>a+Number(p.amount),0);return `<tr><td><b>${s.name}</b></td><td>${s.level}</td><td>${money(s.fees)} ريال</td><td>${money(paid)} ريال</td><td>${money(Math.max(s.fees-paid,0))} ريال</td><td><a class="link" href="statement.html?id=${s.id}">كشف</a> · <button class="link" onclick="openStudent('${s.id}')">تعديل</button> · <button class="link danger" onclick="deleteStudent('${s.id}')">حذف</button></td></tr>`}).join("")||'<tr><td colspan="6">لا توجد نتائج</td></tr>'}
function initPayment(){pDate.value=today();let d=db(),m=settings().methods;pStudent.innerHTML='<option value="">اختر الطالب</option>'+d.students.map(s=>`<option value="${s.id}">${s.name} — ${s.level}</option>`).join("");pMethod.innerHTML=m.map(v=>`<option>${v}</option>`).join("")}
function renderSettings(){let x=settings();levelsList.innerHTML=x.levels.map((v,i)=>`<div class="setting-row"><b>${v}</b><span><button class="link" onclick="editLevel(${i})">تعديل</button> · <button class="link danger" onclick="deleteLevel(${i})">حذف</button></span></div>`).join("");methodsList.innerHTML=x.methods.map((v,i)=>`<div class="setting-row"><b>${v}</b><span><button class="link" onclick="editMethod(${i})">تعديل</button> · <button class="link danger" onclick="deleteMethod(${i})">حذف</button></span></div>`).join("")}
function addLevel(){let v=prompt("اسم المستوى الجديد:");if(!v?.trim())return;let x=settings();if(x.levels.includes(v.trim()))return alert("المستوى موجود");x.levels.push(v.trim());saveSettings(x);renderSettings()}
function editLevel(i){let x=settings(),v=prompt("تعديل اسم المستوى:",x.levels[i]);if(!v?.trim())return;let old=x.levels[i];x.levels[i]=v.trim();let d=db();d.students.forEach(s=>{if(s.level===old)s.level=x.levels[i]});saveDB(d);saveSettings(x);renderSettings()}
function deleteLevel(i){let x=settings(),name=x.levels[i],used=db().students.some(s=>s.level===name);if(used)return alert("لا يمكن حذف مستوى مستخدم من الطلاب. عدّل الطلاب أولاً.");if(!confirm("حذف المستوى؟"))return;x.levels.splice(i,1);saveSettings(x);renderSettings()}
function addMethod(){let v=prompt("اسم طريقة الدفع الجديدة:");if(!v?.trim())return;let x=settings();if(x.methods.includes(v.trim()))return alert("طريقة الدفع موجودة");x.methods.push(v.trim());saveSettings(x);renderSettings()}
function editMethod(i){let x=settings(),v=prompt("تعديل طريقة الدفع:",x.methods[i]);if(!v?.trim())return;let old=x.methods[i];x.methods[i]=v.trim();let d=db();d.payments.forEach(p=>{if(p.method===old)p.method=x.methods[i]});saveDB(d);saveSettings(x);renderSettings()}
function deleteMethod(i){let x=settings(),name=x.methods[i],used=db().payments.some(p=>p.method===name);if(used)return alert("لا يمكن حذف طريقة دفع مستخدمة في عمليات سابقة.");if(!confirm("حذف طريقة الدفع؟"))return;x.methods.splice(i,1);saveSettings(x);renderSettings()}
function renderStatement(){let id=new URLSearchParams(location.search).get("id"),d=db(),s=d.students.find(x=>x.id===id);if(!s){statementTitle.textContent="الطالب غير موجود";return}let ps=d.payments.filter(p=>p.studentId===id).sort((a,b)=>a.date.localeCompare(b.date)),paid=ps.reduce((a,p)=>a+Number(p.amount),0);statementTitle.textContent="كشف حساب — "+s.name;stName.textContent=s.name;stLevel.textContent=s.level;stFees.textContent=money(s.fees);stRemain.textContent=money(Math.max(s.fees-paid,0));statementTable.innerHTML=ps.map((p,i)=>`<tr><td>${i+1}</td><td>${p.date}</td><td>${money(p.amount)} ريال</td><td>${p.method}</td><td>${p.ref||"-"}</td><td>${p.notes||"-"}</td></tr>`).join("")||'<tr><td colspan="6">لا توجد دفعات مسجلة</td></tr>'}
function initFilters(){if(window.payLevel)payLevel.innerHTML='<option value="">كل المستويات</option>'+settings().levels.map(v=>`<option>${v}</option>`).join("");if(window.payMethod)payMethod.innerHTML='<option value="">كل طرق الدفع</option>'+settings().methods.map(v=>`<option>${v}</option>`).join("")}function initSchedule(){if(window.schLevel)schLevel.innerHTML='<option value="">كل المستويات</option>'+settings().levels.map(v=>`<option>${v}</option>`).join("")}
const AUTH_KEY="ghaim_auth_v1", CODE_KEY="ghaim_login_code_v1";
function loginCode(){return localStorage.getItem(CODE_KEY)||"1234"}
function isLoggedIn(){return sessionStorage.getItem(AUTH_KEY)==="1"}
function login(){let c=(loginCodeEl?.value||"").trim();if(c===loginCode()){sessionStorage.setItem(AUTH_KEY,"1");location.href="index.html"}else{loginError.textContent="كود الدخول غير صحيح";loginError.classList.add("show")}}
function logout(){sessionStorage.removeItem(AUTH_KEY);location.href="login.html"}
function changeLoginCode(){let old=prompt("أدخل الكود الحالي:");if(old!==loginCode())return alert("الكود الحالي غير صحيح");let n=prompt("أدخل الكود الجديد (4 أرقام أو أكثر):");if(!n||n.length<4)return alert("الكود يجب أن يكون 4 أرقام أو أكثر");if(!/^\d+$/.test(n))return alert("استخدم أرقامًا فقط");localStorage.setItem(CODE_KEY,n);alert("تم تغيير كود الدخول")}
function protectPage(){if(!isLoggedIn())location.replace("login.html")}
if(!location.pathname.endsWith("/login.html")&&!location.pathname.endsWith("login.html"))protectPage();
